[env]
# REGEX_TITLE="^# +([^\\n\\-=>]*\\w+[^\\n\\-=>]*)(?:[-=]?> *((?:,? *(?:_?[aioubdfghjklmnprstvz]{5})+)+))? *\\n"
# REGEX_ACCESS="^(?:share|access): *((?: *,? *[a-z0-9_]{3,15} +(?:r|w|a|read|write|admin))+) *$"
# REGEX_PROQUINT="(?:_?[aioubdfghjklmnprstvz]{5})+"
# REGEX_USERNAME="^[a-z0-9_]{3,15}$"
# REGEX_PASSWORD="^.{6,64}$"
# REGEX_PROPERTY="^([a-z0-9_]+): (.*)$"
# DB_PATH = "db.json"
# RUST_LOG = "info"