[env]
# REGEX_TITLE = "^# +([^\\n\\-=>]*\\w+[^\\n\\-=>]*)(?:[-=]?> *((?:,? *(?:_?[aioubdfghjklmnprstvz]{5})+)+))? *\\n"
# REGEX_ACCESS = "^(?:share|access): *((?: *,? *[a-z0-9_]{3,15} +(?:r|w|a|read|write|admin))+) *$"
# REGEX_PROQUINT = "(?:_?[aioubdfghjklmnprstvz]{5})+"
# REGEX_USERNAME = "^[a-z0-9_]{3,15}$"
# REGEX_USERNAME_HUMAN = "Characters and digits only, min 3, max 15"
# REGEX_PASSWORD = "^.{6,64}$"
# REGEX_PASSWORD_HUMAN = "Minimum 6, max 64"
# REGEX_PROPERTY = "^([a-z0-9_]+): (.*)$"
# WEB_DIST="web/dist/auth"
# DB_BACKUP_FOLDER="cache/auth_back"
# CACHE_PATH="cache/auth.cache.json"
# DB_PATH="cache/auth.db.json"